# Generated by Django 5.0.3 on 2024-03-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='url',
        ),
    ]
