# Generated by Django 5.0.3 on 2024-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_slider_description_remove_slider_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(default=False, max_length=100),
        ),
    ]
