# Generated by Django 5.0.3 on 2024-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='scpecification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
